ROOT := $(abspath ../)

.PHONY: generate
generate:
	@hyde -g

.PHONY: server
server: generate
	@hyde -w -p 8000 -a 0.0.0.0

.PHONY: clean
clean:
	@rm -rf deploy/

commit: generate
	@git update-ref refs/heads/master origin/master '' 2>/dev/null || true
	@INFO="$$(git describe --all --dirty --long)"; export INFO; \
         GIT_INDEX_FILE=.git/gitindex.tmp; export GIT_INDEX_FILE; \
            rm -f "${ROOT}/$${GIT_INDEX_FILE}" && \
            git add -f "deploy/*" && \
            git update-ref refs/heads/master \
                $$(echo "Autogenerated from $${INFO}" \
                    | git commit-tree $$(git write-tree --prefix=deploy) \
                                -p refs/heads/master)
