ROOT := $(abspath ../)

.PHONY: generate
generate:
	@runhaskell hakyll.hs build

.PHONY: server
server: generate
	@runhaskell hakyll.hs server

.PHONY: clean
clean:
	@runhaskell hakyll.hs clean

commit: generate
	@git update-ref refs/heads/master origin/master '' 2>/dev/null || true
	@INFO="$$(git describe --all --dirty --long)"; export INFO; \
         GIT_INDEX_FILE=.git/gitindex.tmp; export GIT_INDEX_FILE; \
            rm -f "${ROOT}/$${GIT_INDEX_FILE}" && \
            git add -f "_site/*" && \
            git update-ref refs/heads/master \
                $$(echo "Autogenerated from $${INFO}" \
                    | git commit-tree $$(git write-tree --prefix=_site) \
                                -p refs/heads/master)
